### ISSUE TITLE
Some chinese characters in drop-down-list in "Convert Scrapbook data to .zip":

### ISSUE THREAD

**Issue by pascallothar** [danny0838/firefox-scrapbook-converter#5]
In **"Convert Scrapbook data to .zip"**, the choice for _"Top directory name"_ include three possibilities (_**1°**_ _"No top directory"_ greyed out (why???); _**2°**_ _"Scrapbook ID"_; _**3°**_ Something that sounds to be very probably :-) chinese).

Of course, it's not a big problem. Only a feedback.

**Comment by danny0838** [comment]
Fixed in d2436d2f7ffe92f514603bbb299c5fad13baebcf. Thank you for the report.

**Comment by danny0838** [comment]
"No top directory" is disabled because scrapbook data folder contains "index.html", "index.dat", or so. If different ScrapBook items are flushed to the same directory level, they must conflict and overwrite each other.

This option probably only works when there is exactly one ScrapBook data item in the selected import directory.

**Comment by pascallothar** [comment]
Ok, I see.
Thank you for the answer.

Actually, it's even cleaner to have a top directory, especially when you unzip with certain unzipping apps that would put a bunch of files in the work directory.
